name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify:
    strategy:
      matrix:
        go-version: [1.20.x, 1.25.x]
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5,
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        run: make test
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9,
      - name: build
        run: make promwatch
