name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: test
        run: make test
   
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
   
      - name: build
        run: make promwatch
